### ISSUE TITLE
Konzeptphase

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#1]
# Kickoff

### Inhalt

* Json-Schema für das qgsContent.json
* Tabellarische Auflistung aller config.json mit kurzer Beschreibung, was jeweils geändert werden muss.
* Json-Schema und Beispiel-Json für das vereinfachte allgemeingültige permissions.json
* Heutiger Stellenwert der json Schema. Werden diese an irgendeiner Stelle geprüft?
  * Ja, diese werden im Generator gegen die json Schema geprüft
  * Primin macht liste der heutigen json Schema. Diese müssen für AGI bis Projektende im aktuellen unveränderten Stand greifbar bleiben.
* Umgang mit verschiedenen Versionen des json schema
  * Wird von sourcepoe in der Konzeptphase überlegt / entschieden
* Testdaten
  * Ist bis auf Weiteres nicht wichtig. Wenn doch braucht's einen gewissen Vorlauf im AGI zum Bereitstellen --> Schnell melden. 
* Unit-Tests?
  * Wird von sourcepoe in der Konzeptphase überlegt / entschieden
  
### Termine:
* Konzeptunterlagen liegen bis Montagmittag 12. April vor
  * Da wahrscheinlich die Dokumentation in verschiedenen Tickets vorliegen wird, bitte auch ein "Master-Ticket" erstellen, in welchem steht was ich in welchem Ticket lesen soll.

**Comment by pka** [comment]
Besprechung 13.4.21:
- [ ]  JSON-URLS des heutigen Stands mit Version ergänzen @pka

**Comment by pka** [comment]
* Spezifikaton qgsContant als Markdown übernehmen

**Comment by pka** [comment]
Diskussion auf Basis #6:
* Vorgehen Testing:
  - Mit QGIS-Server: WMS-Capablities, FeatureInfo, WFS
  - Styling: manuelle Tests mit ausgewählten GetMap Requests
  - Tests im Intranet SO: benötigt generierte JSONs, wird erst später erfolgen
* Verarbeitung grosser JSON-Files: RAM, Performance
  - produktives `dataProduct.json`: 20MB
  - geschätzte Grösse `qgsContent.json`: ca. 50MB
  - sollte kein Problem sein, RAM-Verbrauch ~200MB ?
* Bis wann sind JSON-Schemas definitiv?
  - Verifizierung via Basis-Implementation json2qgs: 30.4.
  - Erstellung Schema `permission.json`: 30.4.
  - Schema-Erweiterungen für services in jeweilige Repos übernehmen (master-Branch): 30.4.
