### ISSUE TITLE
json2qgs: Schema bzgl. Vektordaten

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#10]
Hoi Matthias

Ich bin soeben grundsätzlich durch mit dem Generieren des json für das qgs. Bekomme noch Validierungsfehler, welche ich nicht so ganz verstehe...

Generiertes json (Relevanter Ausschnitt):

    {
      "name": "ch.so.arp.richtplan.grundnutzung.data",
      "type": "layer",
      "title": "ch.so.arp.richtplan.grundnutzung.data",
      "datatype": "vector",
      "attributes": [
        {
          "name": "grundnutzungsart",
          "alias": ""
        }
      ],
      "qml_assets": null,
      "qml_base64": "",
      "postgis_datasource": {
        "srid": 999,
        "table": "richtplankarte_grundnutzung",
        "schema": "arp_richtplan_pub",
        "unique_key": "t_id",
        "dbconnection": "postgresql:///?service=sogis_services",
        "geometry_type": "dummy",
        "geometry_field": "dummy"
      }
    }

Validierungs-Fehlermeldungen:

    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0: required key [sublayers] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/type: 
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/qml_assets: expected type: JSONArray, found: 
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/postgis_datasource/geometry_type: dummy is not a valid enum value
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0: required key [raster_datasource] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/datatype: 
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0: required key [wms_datasource] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/datatype: 
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0: required key [wmts_datasource] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/layers/0/datatype:

**Comment by mwa** [comment]
Die Validierungsfehler können manchmal etwas zu ausführlich und z.T. irreführend sein.

Hier sind die relevanten Fehler:
* `#/layers/0/qml_assets: expected type: JSONArray, found: `: d.h. `qml_assets` muss zumindest ein leeres Array sein, z.B. `"qml_assets": []`, oder das Feld kann ganz weggelassen werden, da optional
* `#/layers/0/postgis_datasource/geometry_type: dummy is not a valid enum value`: d.h. `geometry_type` muss einen gültigen Wert aus den Enums `"POINT", "LINESTRING", "POLYGON", "MULTIPOINT", "MULTILINESTRING", "MULTIPOLYGON"` haben (vgl. [JSON Schema](https://github.com/simi-so/json2qgs/blob/master/schemas/sogis-wms-qgs-content.json#L270)), z.B. `"geometry_type": "POINT"`

Die übrigen Fehler sind Folgefehler, da nach dem eigentlichen Fehler im `vector_layer` Subschema auch noch die übrigen Subschemas (`productset`, `raster_layer`, ...) geprüft werden, welche ebenfalls nicht erfüllt werden (z.B. `required key [sublayers] not found`). Diese Folgefehler sind aber häufig eher verwirrend als hilfreich.
