### ISSUE TITLE
Permissions: Sicherstellung der Eindeutigkeit

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#11]
Idee für die Sicherstellung der Eindeutigkeit: "Dict" im Schema verwenden, dann kommen Probleme bei der Validierung gegen
das Schema zum vorschein

    {
	    "all_services": {
		    "ch.so.afu.baugrundklassen": false, // Datensatz
		    "ch.so.afu.baugrundklassen": false, // Report zum Datensatz. Report hat gleichen Namen --> Json-Fehler
		    "grundstuecksbeschrieb": false // Anderer Report
	    }
    }

false (oder true) bezieht sich auf writable

**Comment by mwa** [comment]
Die Eindeutigkeit müsste applikatorisch geprüft werden, da dieser Constraint in der JSON Schema Spezifikation nicht zur Verfügung steht. Einzig einfache Arrays von Zahlen oder Strings können mit `"uniqueItems": true` schon im JSON Schema auf Eindeutigkeit geprüft werden.

Ein Dict mit beliebigen Namen als Keys würde das JSON Schema aufweichen, da keine klaren vordefinierten Properties mehr gegeben wären. Es wäre auch nicht mehr konsistent mit den übrigen Schemas, bei denen durchgehend Listen von Objekten mit `name` bzw. `identifier` verwendet werden und nie ein Datenwert als Key.

Zudem werden doppelte Properties je nach Validator nicht zwingend bemängelt. Bei mehrfachen Einträgen wird einfach einer davon benutzt (erster oder letzter). D.h. applikatorisch wären Duplikate nach dem Einlesen des JSON dann gar nicht mehr ersichtlich.
Mit einer Liste von Objekten mit `name` (wie bisher) werden immer alle Einträge eingelesen und es können dabei keine Duplikate verlorengehen und diese damit später erkannt werden.

**Comment by ojeker** [comment]
Applikatorische Prüfung ist wie gesagt kaum möglich, da Datenprodukte und Reports an unterschiedlichsten Ecken im Datenmodell leben.

Was spricht gegen die Ergänzung `"uniqueItems": true`?

**Comment by ojeker** [comment]
Ich habe wie mit Matthias besprochen geprüft, was mit sql2json "passiert". Dabei habe ich festgestellt, dass mit einer einfachen Codeerweiterung sichergestellt werden kann, dass sql2json IMMER ein Fehler wirft bei "dicts" mit Key-Duplikaten. Dies ist nun bereits umgesetzt und getestet.

--> @mwa Bitte darum wie besprochen das Array durch einen dict ersetzen, und nach Abschluss die Doku entsprechend aktualisieren.

**Comment by mwa** [comment]
Siehe https://github.com/simi-so/json2qgs/issues/4#issuecomment-866913238 für aktuelle Beispielkonfiguration und QWC Services

**Comment by ojeker** [comment]
...   
    "ch.so.agi.av.rohrleitungen": {
      "writable": false
    },
    ...

geht auch, oder? (Anstatt weglassen wenn wirtable false ist)

**Comment by mwa** [comment]
Ja, es kann auch explizit `"writable": false` gesetzt werden. Beim Weglassen wird dies sonst auch als Standardwert angenommen.

**Comment by ojeker** [comment]
Passt :)
