### ISSUE TITLE
Doku von pg_service.conf zu QGIS Server Docker Image 2.18

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#15]
Bitte in der Doku auch beschreiben, wie pg_service.conf konfiguriert werden muss, und wie verifiziert werden kann, dass es funktioniert.

### docker-compose:

    version: "3"
    services:
      qgs:
        image: sourcepole/qwc-qgis-server:2.18.28
        environment:
          - QGIS_SERVER_LOG_LEVEL=INFO
        ports:
          - "8081:80"
        volumes:
          - ../.gitignored/pipe_data/qgs_wms:/data:ro
          - ./pg_service.conf:/etc/postgresql-common/.pg_service.conf:ro
      pub:
        image: postgis/postgis:13-3.1-alpine
        environment:
          - POSTGRES_PASSWORD=postgres
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - "5433:5432"
        volumes:
          - "../.gitignored/dbs/pub_pgdat/.pgdata:/var/lib/postgresql/data/pgdata"
          - "../.gitignored/dbs/exchange:/tmp"

### .pg_service.conf

    [sogis_services]
    host=localhost
    port=5432
    dbname=pub
    user=postgres
    password=postgres
    sslmode=disable

## Fehlermeldung bei GetCapabilities-Aufruf:

    qgs_1  | [92][05:39:00] Connection to database failed
    qgs_1  | could not connect to server: No such file or directory
    qgs_1  |        Is the server running locally and accepting
    qgs_1  |        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by pka** [comment]
Funktionierende Konfiguration mit DB in Docker-Container: https://github.com/simi-so/json2qgs/tree/master/tests/docker
