### ISSUE TITLE
Fehler im qwc-ogc-service.json Schema (?)

### ISSUE THREAD

**Issue by EchoCharlie85** [simi-so/json2qgs#18]
Im Schema qwc-ogc-service.json ([Link](https://raw.githubusercontent.com/qwc-services/qwc-ogc-service/master/schemas/qwc-ogc-service.json) steht: 

> "root_layer": {
>                 "description": "Root layer of WMS (layer or group layer)",
>                 "oneOf": [
>                   {"$ref": "#/definitions/wms_layer"},
>                   {"$ref": "#/definitions/wms_group_layer"}
>                 ]
>               },
> 

Dies führt meinen Erfahrungen nach zu einem Fehler bei der Validierung. Meiner Meinung nach müsste es hier heissen: 

> "root_layer": {
>                 "description": "Root layer of WMS (layer or group layer)",
>                 "items": {
>                   "oneOf": [
>                     {"$ref": "#/definitions/wms_layer"},
>                     {"$ref": "#/definitions/wms_group_layer"}
>                   ]
>                 }
>               },

Ist dies korrekt?

**Comment by mwa** [comment]
Der `root_layer` ist entweder ein Einzellayer oder ein einzelner Gruppenlayer, an welchem alle WMS Layer hängen. D.h. `oneOf` bezieht sich hier auf den Typ des `root_layer` selbst. Üblicherweise wird ein Gruppenlayer verwendet, ausser im WMS wäre nur ein einziger Layer enthalten.

Beispiel im `ogcConfig.json`:
```jsonc
    ...
    "wms_services": [
      {
        "name": "somap",
        "online_resources": {
        "root_layer": {
          // WMS Rootlayer als Gruppenlayer (analog WMS GetCapabilities)
          "name": "somap",
          "type": "layergroup",
          "title": "SOMAP",
          "layers": [
            // darunterliegende WMS Layer
            {
              "name": "ch.so.agi.agi_hoheitsgrenzen_pub.hoheitsgrenzen_gemeindegrenze",
              "type": "layer",
              "title": "Gemeindegrenzen",
              ...
            },
            ...
         ]
      }
    ]
```


Bei der Liste der Sublayer eines Gruppenlayers bezieht sich das `oneOf` dagegen auf den Typ der Listenelemente, darum ist es dort innerhalb von `items` im JSON Schema:
```json
        "layers": {
          "description": "Sublayers of this group layer (layers or group layers)",
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "#/definitions/wms_layer"},
              {"$ref": "#/definitions/wms_group_layer"}
            ]
          }
        },
```

**Comment by ojeker** [comment]
Danke für die Erläuterung - Matthias
