### ISSUE TITLE
Json Vaidation Error beim qwc-service

### ISSUE THREAD

**Issue by pfeimich** [simi-so/json2qgs#19]
Beim qwc-service wirft der Json Validator folgenden Fehler

`[main] ERROR ch.so.agi.sql2json.Application - java.io.UncheckedIOException: java.io.FileNotFoundException: https://raw.githubusercontent.com/qgis/qwc2/master/schemas/themes.json`

Hier ist der Pfad zum themes.json im JSON-Schema des qwc-service nicht korrekt

**Comment by mwa** [comment]
Welche Version des JSON Schemas benutzt ihr?

Im Map Viewer JSON Schema gab es kürzlich noch Anpassungen, bei welchen neben den URI Format Constraints auch die Referenzen auf nicht vorhandene externe Schemas entfernt wurden.

Statt [v2](https://raw.githubusercontent.com/qwc-services/qwc-map-viewer/v2/schemas/qwc-map-viewer.json) sollte der aktuelle [master](https://raw.githubusercontent.com/qwc-services/qwc-map-viewer/master/schemas/qwc-map-viewer.json), oder spezifisch versioniert [#3355506](https://raw.githubusercontent.com/qwc-services/qwc-map-viewer/3355506/schemas/qwc-map-viewer.json) benutzt werden.

**Comment by pfeimich** [comment]
Mit den Anpassungen funktioniert es jetzt danke. Das Problem trat schon Mitte letzter Woche auf. Da waren die Anpassungen im master vermutlich noch nicht gemacht.
