### ISSUE TITLE
Übersicht der heutigen (31.03.2021) json schema

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#2]
Liste der Schemas (Stand 31.03.2021):

|Service|Schema URL|Status |
|---|---|---|
| qwc-data-service          | https://github.com/qwc-services/qwc-data-service/raw/master/schemas/qwc-data-service.json                    |        |
| qwc-document-service      | https://github.com/qwc-services/qwc-document-service/raw/master/schemas/qwc-document-service.json            |        |
| qwc-feature-info-service  |https://github.com/qwc-services/qwc-feature-info-service/raw/master/schemas/qwc-feature-info-service.json    |        |
| qwc-legend-service        | https://github.com/qwc-services/qwc-legend-service/raw/v2.0.0/schemas/qwc-legend-service.json                |        |
| qwc-map-viewer            | https://github.com/qwc-services/qwc-map-viewer/raw/master/schemas/qwc-map-viewer.json                        |        |
| qwc-ogc-service           | https://github.com/qwc-services/qwc-ogc-service/raw/master/schemas/qwc-ogc-service.json                      |        |
| qwc-print-service         | https://github.com/qwc-services/qwc-print-service/raw/master/schemas/qwc-print-service.json                  |        |
| qwc-saml-auth             | https://github.com/qwc-services/sogis-config-generator/raw/master/schemas/qwc-saml-auth.json                 |        |
| qwc-search-service        | https://github.com/qwc-services/qwc-fulltext-search-service/raw/master/schemas/qwc-search-service.json       |        |
| sogis-agdi                | https://github.com/qwc-services/sogis-agdi/raw/master/schemas/sogis-agdi.json                                |        |
| sogis-dataproduct-service |https://github.com/qwc-services/sogis-dataproduct-service/raw/master/schemas/sogis-dataproduct-service.json |        |
| qwc-services-permissions  |https://github.com/qwc-services/qwc-services-core/raw/master/schemas/qwc-services-permissions.json           |        |

**Comment by pka** [comment]
Update Status + sogis-ccc-config:

|          Service          |                                                  Schema URL                                                 | Status |
|---------------------------|-------------------------------------------------------------------------------------------------------------|--------|
| qwc-data-service          | https://github.com/qwc-services/qwc-data-service/raw/master/schemas/qwc-data-service.json                   | ok     |
| qwc-document-service      | https://github.com/qwc-services/qwc-document-service/raw/master/schemas/qwc-document-service.json           | #3     |
| qwc-feature-info-service  | https://github.com/qwc-services/qwc-feature-info-service/raw/master/schemas/qwc-feature-info-service.json   | ok     |
| qwc-legend-service        | https://github.com/qwc-services/qwc-legend-service/raw/master/schemas/qwc-legend-service.json               | #3     |
| qwc-map-viewer            | https://github.com/qwc-services/qwc-map-viewer/raw/master/schemas/qwc-map-viewer.json                       | #3     |
| qwc-ogc-service           | https://github.com/qwc-services/qwc-ogc-service/raw/master/schemas/qwc-ogc-service.json                     | ok     |
| qwc-print-service         | https://github.com/qwc-services/qwc-print-service/raw/master/schemas/qwc-print-service.json                 | ok     |
| qwc-saml-auth             | https://github.com/qwc-services/sogis-config-generator/raw/master/schemas/qwc-saml-auth.json                | ok     |
| qwc-search-service        | https://github.com/qwc-services/qwc-fulltext-search-service/raw/master/schemas/qwc-search-service.json      | ok     |
| sogis-agdi                | https://github.com/qwc-services/sogis-agdi/raw/master/schemas/sogis-agdi.json                               | ok     |
| sogis-dataproduct-service | https://github.com/qwc-services/sogis-dataproduct-service/raw/master/schemas/sogis-dataproduct-service.json | ok     |
| sogis-ccc-config          | https://github.com/qwc-services/sogis-ccc-config/raw/master/schemas/sogis-ccc-config.json                   | https://github.com/qwc-services/sogis-ccc-config/pull/3   |
| qwc-services-permissions  | https://github.com/qwc-services/qwc-services-core/raw/master/schemas/qwc-services-permissions.json          | #4   |

**Comment by pka** [comment]
Beispiel JSON-Schema mit Version: https://github.com/qwc-services/qwc-document-service/raw/v2.0.0/schemas/qwc-document-service.json

**Comment by ojeker** [comment]
Ist Info-Issue --> Close
