### ISSUE TITLE
json2qgs: --qgsName wfs generiert wfs_wfs.qgs

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#20]
Hoi Matthias

json2qgs mit --qgsName wfs generiert wfs_wfs.qgs. Erwarten würde ich wfs.qgs

Ich rufe json2qgs wie folgend beschrieben auf:

    #!/bin/bash
    
    source ../../.gitignored/pipe_bin/jqgs/jqgs_venv/bin/activate
    
    python3 ../../.gitignored/pipe_bin/jqgs/json2qgs-master/json2qgs.py \
      ../../.gitignored/pipe_data/qgs/wfs.json \
      wfs \
      ../../.gitignored/pipe_data/qgs \
      2 \
      --qgsName wfs \
      --qgsTemplateDir ../../.gitignored/pipe_bin/jqgs/json2qgs-master/qgs

**Comment by mwa** [comment]
Mit `--qgsName` wird jetzt der vollständige Name des QGS angegeben (ohne `.qgs`), der automatische Suffix entfällt b67207f2
