### ISSUE TITLE
json2qgs: Fassade in Gruppe geht nicht

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#25]
In einer Layergruppe enhaltene Fassadelayer funktionieren nicht.

Hingegen funktioniert:
* Vektorebene direkt in Layergruppe
* "Top-Level" Facadelayer mit Vektorlayern

![image](https://user-images.githubusercontent.com/24891004/125453196-0a25184a-aab5-4d5d-96dd-981c0a3cf12e.png)

QGIS Desktop: Die ersten 5 Ebenen innerhalb der Layergruppe ch.so.arp.nutzungsplanung sind Facadelayer...

![image](https://user-images.githubusercontent.com/24891004/125453849-18acb13b-8537-4d2d-90c6-f6ecd0fa1475.png)

GetCapabilities zeigt die Facadelayer gar nicht...

QGS und Json:
[json2qgs_input_output.zip](https://github.com/simi-so/json2qgs/files/6808920/json2qgs_input_output.zip)

**Comment by mwa** [comment]
Beim Sammeln der Layer wurden die Gruppenlayer nur bis zu einer gewissen Tiefe aufgelöst, so dass die Sublayer dieser Facadelayer fehlten. Jetzt werden beliebig tiefe Layertrees rekursiv vollständig eingelesen  a1c5c03f

Bei fehlenden Layern werden jetzt zudem Warnings ins Log geschrieben (_"Could not find layer '...'"_). Mit `--log_level debug` werden zusätzlich alle verarbeiteten Layer im Log aufgelistet.

Folgende Layer fehlen übrigens in obiger Beispielconfig:
* `ch.so.arp.nutzungsplanung.grundnutzung_oereb`
* `ch.so.arp.nutzungsplanung.ueberlagernd_punkt_oereb`
* `ch.so.arp.nutzungsplanung.ueberlagernd_linie_oereb`
* `ch.so.arp.nutzungsplanung.ueberlagernd_flaeche_oereb`

**Comment by ojeker** [comment]
Danke. 
Dazu noch die folgende Info: Das folgende ist unsere maximal mögliche Verschachtelungstiefe (Bei mehr verstehen wir die Konfiguration selbst nicht mehr und machen Fehler beim Konfigurieren :) )
Layergruppe --> Facadelayer --> Einzellayer
