### ISSUE TITLE
json2qgs: Transparenz, Sichtbarkeit

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#27]
Hallo

Mir ist das Folgende noch nicht klar:
* Wie wird die Transparenz-Einstellung übernommen? Ist im Schema glaubs nicht vorhanden
* Wie wird die Sichtbarkeit von Kindern von Layergruppen übernommen? Ist im Schema glaubs auch nicht vorhanden..

Und: Woher holt sich der Web GIS Client die Information, welche Ebenen einer Gruppe per Default ein- und ausgeschaltet sind (Sichtbarkeit)?

**Comment by mwa** [comment]
Transparenz und Sichtbarkeit sind nicht direkt im QGIS Projekt enthalten, da diese Informationen in den WMS Capabilities selbst nicht vorhanden sind. Beim Anfordern einer Layergruppe werden vom WMS immer alle darin enthaltenen Sublayer angezeigt, auch wenn im QGIS Projekt einzelne Layer ausgeschaltet wären. Ebenso wird die QGIS Layertransparenz im WMS nicht automatisch berücksichtigt.

Erst in den QWC Services werden diese Einstellungen aus den Service Configs angewendet:
* Transparenz:
  * OGC Service: Transparenz von Facade Sublayers bei der internen Auflösung der erlaubten Layer
  * Dataproduct Service / Map Viewer: Transparenzen beim Hinzufügen von Layern oder Themenkarten
* Sichtbarkeit:
  * Dataproduct Service / Map Viewer: Sichtbarkeiten der Einzellayer beim Hinzufügen von Layern oder Themenkarten

In den resultierenden WMS Requests des Map Viewers werden dann die entsprechenden Layer und Opacities angefordert.

**Comment by ojeker** [comment]
Danke Mathias für die Informationen.
