### ISSUE TITLE
json2qgs: Was bestimmt die Reihenfolge der Ebenen im WMS-GetCapabilities?

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#28]
Hintergrund: Im Moment kommen die Ebenen noch "wild durcheinander" daher.

**Comment by mwa** [comment]
Der Layerbaum im QGIS Projekt wird in der gleichen Reihenfolge generiert, wie die Layer in den `wms_top_layers` und  `sublayers` der json2qgs Konfiguration vorkommen. In den WMS Capabilities wird derselbe Layerbaum abgebildet, mit einem zusätzlichen WMS Rootlayer.

Einzelne Layer erscheinen aber nicht in den Capabilities, falls QGIS Server diese nicht laden kann, z.B. bei einer fehlerhaften Datenquelle.
