### ISSUE TITLE
Anforderung als jpeg schlägt bei Custom-Legend fehl

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#29]
Ciao mitenand

Beim Laden einer WMS-Ebene mit imagetype jpeg und Custom-Legende wird:
* Die Karte korrekt dargestellt
* Die Legendendarstellung schlägt fehl (Anzeige von "Connection closed" in QGIS Desktop)

Im Anhang das vom Legend-Service generierte log. Ich vermute, der Legend-Service kann mit der Anforderung als jpeg nicht umgehen (Bei Anforderung als PNG funktioniert alles):

[jpeg_png_error.txt](https://github.com/simi-so/json2qgs/files/6890729/jpeg_png_error.txt)

![image](https://user-images.githubusercontent.com/24891004/127272144-a77fde72-0dcd-4b1e-ad1f-4f67cea6f912.png)

**Comment by mwa** [comment]
Custom Legenden mit RGBA werden jetzt auch für angeforderte Formate ohne Transparenz (z.B. JPEG) unterstützt.

Gefixt in `qwc-legend-service:v2.0.4`
