### ISSUE TITLE
dataprod service: qml, description, .. base64 codiert einlesen

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#30]
Dem dataprod-service fehlt das glaubs noch...

Bitte:
* Prüfen, ob es neben qml und description noch weitere "heikle" inputs gibt
* Für alle heiklen inputs die Informationen als x_base64 entgegennehmen

Die output signaturen des service müssen (natürlich) unverändert codiert bleiben.

**Comment by mwa** [comment]
Ab `sogis-dataproduct-service:v2.0.9` können jetzt `description` und `qml` auch als Base64 encodierte Config Properties gesetzt werden:

```jsonc
{
  "identifier": "ch.so.awjf.waldstandorte.waldstandorte",
  ...
  // "description": "Beschreibung des Dataproducts",
  "description_base64": "QmVzY2hyZWlidW5nIGRlcyBEYXRhcHJvZHVjdHM=",
  ...
  // "qml": "<qgis hasScaleBasedVisibilityFlag=\"0\" maxLabelScale=\"1e+08\" maximumScale=\"1e+08\" ...",
  "qml_base64": "PHFnaXMgaGFzU2NhbGVCYXNlZFZpc2liaWxpdHlGbGFnPSIwIiBtYXhMYWJlbFNjYWxlPSIxZSswOCIgbWF4aW11bVNjYWxlPSIxZSswOCIgLi4u",
  ...
}

```

**Comment by ojeker** [comment]
Danke

Im Schema gibt es noch ein kleines Problem: Einer der Description-Keys muss nun vorhanden sein. Sollte weiterhin optional sein.

    [main] INFO ch.so.agi.sql2json.Application - Validating against schema https://raw.githubusercontent.com/qwc-services/sogis-dataproduct-service/master/schemas/sogis-dataproduct-service.json
    [main] ERROR ch.so.agi.sql2json.validation.Validator - Validation against json schema failed with 7 errors. See following detail messages.
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/31: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/31: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/32: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/32: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/33: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/33: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/34: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/34: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/35: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/35: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/36: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/36: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/37: required key [description] not found
    [main] ERROR ch.so.agi.sql2json.validation.Validator - #/resources/dataproducts/37: required key [description_base64] not found
    [main] ERROR ch.so.agi.sql2json.Application - Exception occured. Exiting...

**Comment by mwa** [comment]
Im `master` (`sogis-dataproduct-service:v2.0.10`) ist die Beschreibung (`description` oder `description_base64`) jetzt optional.
