### ISSUE TITLE
json2qgs: Namenskollisionen bei den exportierten Assets

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#32]
Problem: Die Assets (*.svg, ..) werden ohne Unterordnerstruktur in den gleichen Ordner wie das *.qgs gelegt. Dies kann zu Namneskollisionen führen.

Lösung??: json2qgs erstellt Unterordner mit dem Namen der Ebene, und legt die Assets in die Unterordner.

**Comment by mwa** [comment]
Die Assets werden jetzt für jeden Layer in einem separaten Unterverzeichnis abgelegt und die Symbolpfade im QGS entsprechend angepasst (z.B. `fillpattern/myPattern.png` => `afu_altlasten_pub/fillpattern/myPattern.png`).

Implementiert in ae2b09a4
