### ISSUE TITLE
dataprod-service gibt im endpunkt /maplayers das abstract als base64 aus

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#35]
ZU BEACHTEN: Tritt nur bei Layergruppen auf. Facadelayer und Einzellayer funktionieren korrekt

Erwartetes verhalten: Ausgabe wie in den Versionen vor base64 - glaubs mit custom escaping...

Request:

    https://geo-t.so.ch/api/dataproduct/v1/weblayers?filter=ch.so.agi.av.amtliche_vermessung

Response (Ausschnitt)

    {
        "ch.so.agi.av.amtliche_vermessung": [
            {
                "name": "ch.so.agi.av.amtliche_vermessung",
                "title": "Amtliche Vermessung",
                "abstract": "RGllIGFtdGxpY2hlIFZlcm1lc3N1bmcgaMOkbHQgYWxzIEJlc3RhbmR0ZWlsIGRlcyBHcnVuZGJ1\nY2hlcyBkaWUgZ2VuYXVlbiBHcmVuenZlcmzDpHVmZSBkZXIgR3J1bmRzdMO8Y2tlIGZlc3QgdW5k\nIHNjaGFmZnQgZGFtaXQgZGllIEJhc2lzIHp1ciBTaWNoZXJ1bmcgZGVzIEdydW5kZWlnZW50dW1z\nLiBOZWJzdCBkZW4gYWt0dWVsbGVuIEdydW5kc3TDvGNrc2dyZW56ZW4gc2luZCBpbiBkZW4gRGF0\nZW4gZGVyIGFtdGxpY2hlbiBWZXJtZXNzdW5nIGF1Y2ggd2VpdGVyZSBPYmpla3RlIHdpZSBHZWLD\npHVkZSwgU3RyYXNzZW4sIEdlYsOkdWRlYWRyZXNzZW4gdXN3LiBhYmdlYmlsZGV0Lg==",
                "visibility": true,

**Comment by mwa** [comment]
Beim Auslesen der Beschreibung wird nicht zwischen den Layertypen unterschieden, darum sollte das bei Layergruppen ebenfalls funktionieren.

Wie sieht die zugehörige Konfiguration im `dataproductConfig.json` aus?

Falls ein Base64 Wert nicht dekodiert werden kann, wird im Service Log ein Fehler mit der Ursache angezeigt und der originale Wert zurückgegeben. Obiges Beispiel kann aber korrekt dekodiert werden (trotz Newlines `\n` im Base64 String). Allenfalls wird beim Generieren der Config bei Layergruppen fälschlicherweise immer noch `description` statt `description_base64` als Property gesetzt?

**Comment by ojeker** [comment]
Danke - da generieren hat für die Layergruppen noch description ausgegeben. Ist mir leider nicht vorher als mögliche Ursache in den Sinn gekommen.
