### ISSUE TITLE
dataproduct service: Auslieferung svg als base64

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#37]
Ciao Mathias

Wir haben noch einen offenen Punkt bei den svg-Symbolen für QGIS-Desktop.

Request (Testsystem):

`https://geo-t.so.ch/api/dataproduct/v1/ch.so.afu.geologie.schichtfallen`

Testsystem: Ausschnitt aus Response der property "qml":

`"qml":"....<prop k=\"name\" v=\"Pfeil_Schwarz.svg\"/>...."`

Prodsystem: Ausschnitt aus Response der property "qml":

`"qml":"....<prop k=\"name\" v=\"base64:PD94bWwgdmVyc2lvbj0iMS4wIj8+CjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cjxzdmcgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPGxpbmUgeDE9IjIwIiB5MT0iMCIgeDI9IjIwIiB5Mj0iNDAiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSI0Ii8+CiAgPGxpbmUgeDE9IjEwIiB5MT0iMTAiIHgyPSIyMCIgeTI9IjAiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSI0Ii8+IAogIDxsaW5lIHgxPSIzMCIgeTE9IjEwIiB4Mj0iMjAiIHkyPSIwIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iNCIvPiAKPC9zdmc+Cg==\" />...."`

Wie müssen die svg's im dataproductConfig.json übergeben werden, damit der dataproduct service das replacement macht? In der Doku habe ich nichts gefunden bezüglich der svg's im dataproductConfig.json...

Vüw Grüess
Oliver

**Comment by mwa** [comment]
Implementiert in `sogis-dataproduct-service:v2.0.11`

Konfiguration analog json2qgs Config:
```json
      "qml_assets": [
        {
          "path": "fillpattern/myPattern.png",
          "base64": "iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAHUlEQVQI12NgwAEYGRgY/tdjiDYyMOHSQQ8JnAAAUUoCDCaibn8AAAAASUVORK5CYII="
        },
        {
          "path": "svg/myCircle.svg",
          "base64": "PHN2ZyBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA1ODAgNTgwIiBoZWlnaHQ9IjU4MCIgdmlld0JveD0iMCAwIDU4MCA1ODAiIHdpZHRoPSI1ODAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgY3g9IjI5MS4zMTQiIGN5PSIyOTIuNDY2IiBmaWxsPSJwYXJhbShmaWxsKSIgcj0iMjczLjI2MSIgc3Ryb2tlPSJwYXJhbShvdXRsaW5lKSIgc3Ryb2tlLXdpZHRoPSJwYXJhbShvdXRsaW5lLXdpZHRoKSIvPgo8L3N2Zz4K"
        }
      ]
```
