### ISSUE TITLE
Bitte in diesem Ticket die Versionen der Images (für den Milestone) dokumentieren

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#39]
Versionen: ...

**Comment by mwa** [comment]
Aktuelle QWC Services:
* `qwc-data-service:v2.0.7`
* `qwc-document-service:v2.0.3`
* `qwc-elevation-service:v2.0.0`
* `qwc-feature-info-service:v2.0.7`
* `qwc-fulltext-search-service:v2.1.2`
* `qwc-legend-service:v2.0.4`
* `qwc-mapinfo-service:v2.0.0`
* `qwc-ogc-service:v2.0.5`
* `qwc-permalink-service:v2.0.0`
* `qwc-print-service:v2.0.2`
* `sogis-agdi:v3.0.1`
* `sogis-auth-service:v3.0.0`
* `sogis-ccc-config:v2.0.1`
* `sogis-dataproduct-service:v2.0.11`
* `sogis-landreg-service:v2.0.0`
* `sogis-map-viewer:v2.0.12`  _(Standard QWC2: `qwc-map-viewer:v2.0.4`)_
* `sogis-plotinfo-service:v2.0.1`

zusätzliche Images:
* `jasper-reporting-service:0.8.0`
* `solr:8.4.1` oder `solr.latest`
