### ISSUE TITLE
json2qgs: WMSMaxHeight und WMSMaxWidth

### ISSUE THREAD

**Issue by pfeimich** [simi-so/json2qgs#40]
Wir benötigen die Parameter **WMSMaxHeight** und **WMSMaxWIdth** im qgs.
Zunächst die Frage: Wird **WMSMaxHeight** und **WMSMaxWidth** in QGIS Server 2.18 bereits unterstützt?
Laut [https://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/ogc_server_support.html](https://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/ogc_server_support.html) wohl ja.

Falls ja bitte in json2qgs implementieren.
Definition der Werte via [https://raw.githubusercontent.com/simi-so/json2qgs/master/schemas/sogis-wms-qgs-content.json](https://raw.githubusercontent.com/simi-so/json2qgs/master/schemas/sogis-wms-qgs-content.json)

Danke

**Comment by mwa** [comment]
Implementiert in 050cc39d (`json2qgs:v1.0.1`).

Neue optionale Konfiguration:
```jsonc
{
  ...
  "wms_max_width": 8196,
  "wms_max_height": 8196,
  ...
}
```

**Comment by pfeimich** [comment]
Funktioniert
