### ISSUE TITLE
Fragen / Erfahrungen mit permission.json

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#8]
/*
 * Fragen sourcepole
 * - Null-Werte anstelle [] für user.group, user.role und group.role
 * - Typo: writable anstatt writeable
 * - Raster-Datasetview müssen unterhalb Dataproducts nicht aufgelistet werden oder? (Sie bestehen nur aus dem Identifier)
 * 
 */

**Comment by mwa** [comment]
* wir können das JSON Schema und den Permissions Reader so anpassen, dass auch `null` für `user.groups`, `user.roles` und `group.roles` erlaubt ist
* beide Schreibweisen sind korrekt, in den bisherigen Permissions wird ebenfalls `writable` benutzt
* Rasterdatasets müssen nicht nochmals in `dataproducts` aufgeführt werden (analog Document Templates). Wenn keine `sublayers` oder `attributes` benötigt werden, wird der Identifier direkt übernommen, ohne Lookup in `dataproducts`.
