### ISSUE TITLE
QGS WFS: Metadaten: Dokumentation, allenfalls Schemaanpassung

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#9]
Ich habe soeben via sql2json das Json für QGS WFS generiert.

Bei der Validierung gegen das Schema hat es von mir wfs_metadata.online_resource verlangt.

Bitte:
* Alle nicht zwingend notwendigen Metainformationen auf nullable setzen (Im Schema)
* Die einzelnen Elemente des qgsContent.json für wfs in einem *.md beschreiben (inkl. der Metadatenfelder)
  * Zwecks Erläuterung das Beispiel aus dem Ticket verwenden - das ist super.

**Comment by mwa** [comment]
* WMS und WFS Metadaten unterstützen jetzt auch `null`-Werte (ausser `bbox`). Die meisten Properties können wie bisher auch ganz weggelassen werden, statt sie auf `null` zu setzen. (761377f3)
* Beispielkonfigurationen mit Kommentaren zum README hinzugefügt (3912bf14)

**Comment by ojeker** [comment]
Super - Danke
Kannst du bzgl den Metadaten noch ergänzen, welche Informationen zwingend sind (nicht weggelassen werden können)?

Und: Falls nicht sehr kompliziert das json schema bitte so gestalten, dass für die nicht zwingenden Metadaten auch null akzeptiert wird (Falls nicht eh schon der Fall).

**Comment by mwa** [comment]
Die Metadaten sind alle optional, wobei in `wms_metadata` ein wert für `"root_name": "somap"` gesetzt werden sollte, damit auch der WMS Rootlayer von externen WMS Clients angefordert werden kann. Im QWC2 selbst hat dies aber keine Auswirkung, da immer eine spezifische Layerauswahl benutzt wird.

Defaultwerte der Metadaten, falls nicht vorhanden oder auf `null` gesetzt:
* `"keywords": null`
* `"crs_list": ['EPSG:2056']` (nur WMS)
* `"bbox": {"bounds": [2590983, 1212806, 2646267, 1262755]`, "srid": 2056}`
* übrige Properties: `''` (leerer String)

Im JSON Schema werden `null`-Werte in den Metadaten bereits unterstützt.
